// app/layout.tsx
import type { Metadata } from 'next'
import { ErrorWrapper } from './error-wrapper'
import "./globals.css"

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codeevolution",
    
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem"
        }}
      >
        <p>Header</p>
      </header>
        <main>
          <ErrorWrapper>
             {children}
          </ErrorWrapper>
        </main>

        <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem"
        }}
      >
        <p>Footer</p>
      </footer>
      </body>
      
    </html>
  )
}