// app/layout.tsx
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <main>{children}</main>

        <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem"
        }}
      >
        <p>Footer</p>
      </footer>
      </body>
      
    </html>
  )
}